#ifndef _MUART_CONFIG_H_
#define _MUART_CONFIG_H_

#define MUART_BAUDRATE				MUART_U8_BAUDRATE_9600
#define MUART_CHARACTER_SIZE		MUART_8_BIT
#define MUART_PARITY				MUART_NO_PARITY
#define MUART_STOP_BIT				MUART_STOP_1BIT
#define MUART_MODE					MUART_ASYNCH

#define MUART_DOUBLE_SPEED			0
#define MUART_MULTI_PROCESSOR		0

#define MUART_RX_INT_EN				0
#define MUART_TX_INT_EN				0
#define MUART_UDR_EMPTY_INT_EN		0

#define MUART_CLK_POLARITY			MUART_POL_CHANGE_SAMPLE



#endif
